/**
 * [SYSTEM GENERATED]: IMAGE_BLUR_REGISTRY v2026-02-18T17:35:32.217Z
 * [MANDATE]: Strictly Auto-Generated by scripts/gen-blur-data.mjs.
 * [STRATEGY]: Static BlurHash for Zero-CLS LCP.
 */
import type { ImageBlurRegistry } from "@/types";

export const IMAGE_BLUR_DATA: ImageBlurRegistry = {
  "/images/areas/bangkok-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/chiang-mai-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/chiang-rai-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/chon-buri-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/chumphon-gateway.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/kamphaeng-phet-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/khon-kaen-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/korat-monolith.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/korat-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/lampang-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/mae-hong-son-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/nakhon-sawan-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/phang-nga.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/phichit-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/phitsanulok-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/phuket-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/preview.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/ranong-hotspring.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/sukhothai-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/surat-ratchaprapha.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/tak-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/areas/uttaradit-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/avatar.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoKAAoABUB8JYgCw7ELX8pfUAAA/u3f+dBkd0jL+/Z/RkpYE1XeQ5dhrMuqAu2RR2agAAAA",
    "width": 554,
    "height": 554
  },
  "/images/blog/advanced-schema-markup.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/blog/copywriting-specialist.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/blog/core-web-vitals-speed.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/blog/default-thumb.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/blog/ecommerce-seo.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/blog/facebook-ads-vs-website.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAAcABUB8JZgCdADdKOSPv0gA/tBoIlOWILsosq9XmVWHJfD4AA==",
    "width": 696,
    "height": 495
  },
  "/images/blog/seo-google-love.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JYwCdH8AFx7S4QAA/u46rN37K4uMFz8bDUlvGpzjD+XFgO+I5FKehiDgAA==",
    "width": 640,
    "height": 479
  },
  "/images/blog/technical-audit-visual.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAcABUB8JYwCdH8AFx7S4QAA/u46rN37K4uMFz8bDUlvGpzjD+XFgO+I5FKehiDgAA==",
    "width": 640,
    "height": 479
  },
  "/images/case-studies/default.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/case-studies/industrial-catalog.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/case-studies/preview.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/case-studies/provincial-domination.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/case-studies/unlink-reputation.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAAcABUB8JZgCdADdKOSPv0gA/tBoIlOWILsosq9XmVWHJfD4AA==",
    "width": 696,
    "height": 495
  },
  "/images/experts/profile-hero.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/logo-main.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/og-blog.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/og-case-studies.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/og-default.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/og-main.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/seo/advanced-schema-markup.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/seo/core-web-vitals-speed.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/seo/ecommerce-seo.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/seo/seo.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/services/bio-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/services/catalog-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/services/corporate-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/services/default.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoKAAgABUB8JYwCdADc9U44QAD+5a3vLwE2CvtSvGyaza+hIrPt9vL8MAA=",
    "width": 1024,
    "height": 768
  },
  "/images/services/hotel-resort-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/services/local-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/services/personal-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/services/salepage-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoKAAgABUB8JZwAA3AA/vAEDO62XxaCgAA=",
    "width": 1024,
    "height": 768
  },
  "/images/services/seo-agency-node.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  },
  "/images/shared/placeholder.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoKAAcABUB8JZgCdADdKOSPv0gA/tBoIlOWILsosq9XmVWHJfD4AA==",
    "width": 696,
    "height": 495
  },
  "/images/shared/preview.webp": {
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAABwAQCdASoKAAgABUB8JZgCdAF1AAD+8EJsrNup/MqA/NKpKjAxJKbn9ODGAAAA",
    "width": 1024,
    "height": 768
  }
} as const;
