#!/bin/bash

# ==============================================================================
# PROJECT: www.aemdevweb.com
# DESCRIPTION: Project Structure Reporter (Technical Documentation Generator)
# VERSION: 2.1.0 (2026-01-22)
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="aemdevweb-tree.md"
PROJECT_DOMAIN="www.aemdevweb.com"
PROJECT_URL="https://www.aemdevweb.com"

# Next.js 15 Enterprise Directory Whitelist
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
  "viewport"
)

# Root-level configuration files (Validated)
ROOT_FILES=(
  "eslint.config.mjs"
  "mdx-components.tsx"
  "next.config.mjs"
  "package.json"
  "components.json"
  "tsconfig.json"
  "postcss.config.mjs"
  "middleware.ts"
)

# Ignore non-essential patterns
IGNORE_PATTERN="node_modules|\.git|\.next|\.DS_Store|__pycache__|\.env"

# EXECUTION
rm -f "$OUTPUT_FILE"
echo "[INFO] Scanning $PROJECT_DOMAIN project architecture..."

{
  echo "---"
  echo "domain: $PROJECT_DOMAIN"
  echo "canonical: $PROJECT_URL"
  echo "generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "type: Architecture Documentation"
  echo "---"
  echo ""
  echo "# Project Structure Report"
  echo ""
  echo "Project: $PROJECT_DOMAIN"
  echo "URL: $PROJECT_URL"
  echo "Report Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  # --- 1. ROOT CONFIGURATION ---
  echo "## 1. Root Configuration Files"
  echo "The following system files are detected at the project root."
  echo ""

  for file in "${ROOT_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "- [x] $file"
    else
      echo "- [ ] $file (Not found)"
    fi
  done
  echo ""

  # --- 2. ARCHITECTURAL TREE ---
  echo "## 2. Directory Structure"
  echo "Hierarchical view of core business logic and UI components."
  echo ""

  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "### Folder: $dir"
      echo '```text'
      find "$dir" -maxdepth 5 -not -path '*/.*' | grep -vE "$IGNORE_PATTERN" | sed -e 's/[^-][^\/]*\//  |/g' -e 's/|  /   /g'
      echo '```'
      echo ""
    fi
  done

  echo "---"
  echo "Report generated by $PROJECT_DOMAIN Internal Automation."

} > "$OUTPUT_FILE"

echo "[SUCCESS] Structure report saved to -> $OUTPUT_FILE"
