#!/bin/bash

# ==============================================================================
# PROJECT: aemdevweb.com - Full Context & Code Analysis Script
# DESCRIPTION: Compiles architectural structure and critical source code.
# VERSION: 2.0.0 (2026-01-22)
# ==============================================================================

# CONFIGURATION
OUTPUT_FILE="aemdevweb-summary-with-code.md"
REPORT_FILE="pre-deploy-report.md"
PROJECT_DOMAIN="www.aemdevweb.com"
PROJECT_URL="https://aemdevweb.com"

# Next.js 15 Enterprise Directory Whitelist
WHITELIST_DIRS=(
  "app"
  "actions"
  "components"
  "lib"
  "hooks"
  "types"
  "scripts"
  "public"
  "data"
  "constants"
  "providers"
  "content"
  "styles"
  "services"
  "config"
)

# Critical files for AI context analysis
SCAN_FILES=(
  "config/ai-context.core.md"
  "config/ai-system-role.md"
  "config/ai-context.dna.md"
  "$REPORT_FILE"
  "app/globals.css"
  "app/layout.tsx"
  "app/(main)/page.tsx"
  "app/middleware.ts"
  "app/instrumentation.ts"
  "components/landing/HomeClientSections.tsx"
  "app/(marketing)/[template]/[category]/[slug]/page.tsx"
  "app/(main)/blog/[slug]/page.tsx"
  "constants/site-config.ts"
  "constants/services-data.ts"
  "constants/navigation.ts"
  "tsconfig.json"
  "package.json"
  "types/index.ts"
  "next.config.mjs"
  "components.json"
  "lib/blog.ts"
  "lib/template.ts"
  ".env"
)

# INITIALIZATION
rm -f "$OUTPUT_FILE"
echo "[INFO] Initiating Full Context Scan for $PROJECT_DOMAIN..."

{
  echo "# Project Context Summary (Full Scan)"
  echo ""
  echo ""
  echo ""
  echo "Generated on: $(date '+%Y-%m-%d %H:%M:%S')"
  echo "Project: $PROJECT_DOMAIN"
  echo "URL: $PROJECT_URL"
  echo "Status: Production-Ready Analysis | Full System Context"
  echo ""

  # --- 1. PROJECT HEALTH STATUS ---
  echo "## 1. Project Health and Deployment Readiness"
  if [ -f "$REPORT_FILE" ]; then
    if grep -q "### READY FOR DEPLOY" "$REPORT_FILE"; then
      echo "STATUS: READY FOR DEPLOY (Project meets production standards)"
    else
      echo "STATUS: FIX REQUIRED (Check issue highlights)"
    fi
    echo ""

    if grep -q "### Route Statistics" "$REPORT_FILE"; then
      echo "### Production Route Map"
      echo '```text'
      sed -n '/### Route Statistics/,/---/p' "$REPORT_FILE" | \
        grep -v "###" | grep -v -- "---" | sed '/^$/d'
      echo '```'
    fi
  else
    echo "WARNING: $REPORT_FILE not found. Run pre-deploy-check.sh for metrics."
  fi
  echo ""

  # --- 2. FILE TYPE DISTRIBUTION ---
  echo "## 2. File Statistics by Extension"
  echo '```text'
  find "${WHITELIST_DIRS[@]}" -type f 2>/dev/null \
    | sed 's/.*\.//' | sort | uniq -c | sort -nr
  echo '```'
  echo ""

  # --- 3. ARCHITECTURAL TREE ---
  echo "## 3. Directory Structure (Architecture Tree)"
  echo '```text'
  for dir in "${WHITELIST_DIRS[@]}"; do
    if [ -d "$dir" ]; then
      echo "dir: $dir/"
      find "$dir" -maxdepth 4 -not -path '*/.*' | sed -e 's/[^-][^\/]*\//  |/g' -e 's/|  /   /g'
    fi
  done
  echo '```'
  echo ""

  # --- 4. SOURCE CODE & TECHNICAL CONTEXT ---
  echo "## 4. Critical Code Analysis and Environment"
  for file in "${SCAN_FILES[@]}"; do
    if [ -f "$file" ]; then
      echo "### File: $file"

      ext="${file##*.}"
      lang="text"
      case "$ext" in
        ts|tsx) lang="typescript" ;;
        js|mjs) lang="javascript" ;;
        json) lang="json" ;;
        md) lang="markdown" ;;
        css) lang="css" ;;
        sql) lang="sql" ;;
      esac

      echo '```'"$lang"
      if [[ "$file" == *".env"* ]]; then
        # Securely mask sensitive data
        sed 's/=\(.*\)/= "REDACTED"/' "$file"
      elif [ "$file" = "package.json" ] && command -v jq >/dev/null 2>&1; then
        jq '{name, version, scripts, dependencies, devDependencies}' package.json
      else
        cat "$file"
      fi
      echo '```'
      echo "---"
      echo ""
    fi
  done

  echo "## Summary"
  echo "Architecture scan and context compilation completed successfully."
  echo "Focus: Privacy, Security, and AI-readiness."
  echo ""
  echo "Report generated by $PROJECT_DOMAIN Internal Automation."

} > "$OUTPUT_FILE"

echo "[SUCCESS] Full Scan Complete! Report saved to -> $OUTPUT_FILE"
